services:
  db:
    image: postgis/postgis:16-3.4
    container_name: visual_battle_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: visual_battle
      POSTGRES_USER: visual_battle_user
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - visual_battle_pgdata:/var/lib/postgresql/data
volumes:
  visual_battle_pgdata:
